spring:
  kafka:
    bootstrap-servers: 47.75.33.177:9092,47.75.176.97:9092,47.75.170.254:9092
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.27.211.197:3306/blz?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: kaifa_A
    password: 2cyNKp%DHYhnGQfu
    hikari:
      connection-timeout: 30000
      max-lifetime: 60000
  influxdb:
    url: http://47.75.120.236
    port: 8086
    user-name: root
    password: admin
    data-base: TopCoinDB
    retention-policy: autogen
    gzip: true
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10
  redis:
    host: 47.97.169.136
    port: 6379
    password: redis
    database: 0
    pool:
      max-active: 800   # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8       # 连接池中的最大空闲连接
      min-idle: 0       # 连接池中的最小空闲连接
      timeout: 0        # 连接超时时间（毫秒）
logging:
  level:
    root: info
    com.al.exchange: info
    com.al.exchange.kafka: info