package com.al.exchange.dao.mapper;

import com.al.exchange.dao.domain.ExchangeBook;
import com.al.exchange.dao.domain.ExchangeBookExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExchangeBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    long countByExample(ExchangeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int deleteByExample(ExchangeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer sort);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int insert(ExchangeBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int insertSelective(ExchangeBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    List<ExchangeBook> selectByExample(ExchangeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    ExchangeBook selectByPrimaryKey(Integer sort);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExchangeBook record, @Param("example") ExchangeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExchangeBook record, @Param("example") ExchangeBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExchangeBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExchangeBook record);
}