package com.al.exchange.dao.mapper;

import com.al.exchange.dao.domain.InformationMarketcap;
import com.al.exchange.dao.domain.InformationMarketcapExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InformationMarketcapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    long countByExample(InformationMarketcapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int deleteByExample(InformationMarketcapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int insert(InformationMarketcap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int insertSelective(InformationMarketcap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    List<InformationMarketcap> selectByExample(InformationMarketcapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    InformationMarketcap selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InformationMarketcap record, @Param("example") InformationMarketcapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InformationMarketcap record, @Param("example") InformationMarketcapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationMarketcap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_marketcap
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationMarketcap record);
}