package com.al.exchange.dao.mapper;

import com.al.exchange.dao.domain.OnlyKeysMapDto;
import com.al.exchange.dao.domain.OnlykeyBean;
import com.al.exchange.dao.domain.OnlykeyBeanExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface OnlykeyBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    long countByExample(OnlykeyBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int deleteByExample(OnlykeyBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int insert(OnlykeyBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int insertSelective(OnlykeyBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    List<OnlykeyBean> selectByExample(OnlykeyBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    OnlykeyBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OnlykeyBean record, @Param("example") OnlykeyBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OnlykeyBean record, @Param("example") OnlykeyBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OnlykeyBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table onlykey
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OnlykeyBean record);


    @Select("select only_key as onlyKey ,all_name as allName,m_kline_conf as mKlineConf,d_kline_conf" +
            " as dKlineConf,price_conf as priceConf,high_low_conf as highLowConf,vol_conf as volConf,indicator_from as indicatorFrom from only_keys_conf")
    List<OnlyKeysMapDto> getOnlyKeyAndName();
}