package com.al.exchange.dao.domain;

public class InformationMarketcap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_marketcap.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_marketcap.name_self
     *
     * @mbg.generated
     */
    private String nameSelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_marketcap.name_own
     *
     * @mbg.generated
     */
    private String nameOwn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_marketcap.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_marketcap.id
     *
     * @return the value of information_marketcap.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_marketcap.id
     *
     * @param id the value for information_marketcap.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_marketcap.name_self
     *
     * @return the value of information_marketcap.name_self
     *
     * @mbg.generated
     */
    public String getNameSelf() {
        return nameSelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_marketcap.name_self
     *
     * @param nameSelf the value for information_marketcap.name_self
     *
     * @mbg.generated
     */
    public void setNameSelf(String nameSelf) {
        this.nameSelf = nameSelf == null ? null : nameSelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_marketcap.name_own
     *
     * @return the value of information_marketcap.name_own
     *
     * @mbg.generated
     */
    public String getNameOwn() {
        return nameOwn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_marketcap.name_own
     *
     * @param nameOwn the value for information_marketcap.name_own
     *
     * @mbg.generated
     */
    public void setNameOwn(String nameOwn) {
        this.nameOwn = nameOwn == null ? null : nameOwn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_marketcap.symbol
     *
     * @return the value of information_marketcap.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_marketcap.symbol
     *
     * @param symbol the value for information_marketcap.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }
}